In [12]:
import os
from PIL import Image
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
# Split set
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelBinarizer

# Path to image folders, 
data_path = fr'../Datasets/train'
# os.listdir(data_path)

def remove_white_background(pixels):
    for pixel in pixels:
        pixel = list(pixel)
        if ((256 > pixel[0] > 200) and (256 > pixel[1] > 200) and (256 > pixel[2] > 200)):
            pixel[0] = 0
            pixel[1] = 0
            pixel[2] = 0

    return pixels


def redify(pixels):
    return [r for r, g, b in pixels]

                
def greenify(pixels):
    return [g for r, g, b in pixels]



def blueify(pixels):
    return [b for r, g, b in pixels]


def get_rgb_pixels_labels(src):
    print("Starting...")
    newPixels = []
    y = np.empty(shape=[0, 1])

    for subdir in os.listdir(src):
        current_path = os.path.join(src, subdir)
        for file in os.listdir(current_path):
            img = Image.open(os.path.join(current_path, file))
            imgResize = img.resize((24,24))
            pixels = list(imgResize.getdata())
            pixels = remove_white_background(pixels)
            newPixels.append(pixels)
            y = np.append(y, subdir)
    print(LabelBinarizer().fit_transform(y))
    return newPixels, LabelBinarizer().fit_transform(y) # OneHot encode y

def process_files(src):
    X_red = []
    X_green = []
    X_blue = []
    all_pixels, y = get_rgb_pixels_labels(src)
    
    for pixels in all_pixels:
        X_red.append(redify(pixels.copy()))
        X_green.append(greenify(pixels.copy()))
        X_blue.append(blueify(pixels.copy()))
    
    X_red_train, X_red_test, y_red_train, y_red_test = train_test_split(np.asarray(X_red), y, test_size=0.20, random_state=1)
    X_red_train, X_red_validation, y_red_train, y_red_validation = train_test_split(X_red_train, y_red_train, test_size=0.25, random_state=1)

    X_green_train, X_green_test, y_green_train, y_green_test = train_test_split(np.asarray(X_green), y, test_size=0.20, random_state=1)
    X_green_train, X_green_validation, y_green_train, y_green_validation = train_test_split(X_green_train, y_green_train, test_size=0.25, random_state=1)    

    X_blue_train, X_blue_test, y_blue_train, y_blue_test = train_test_split(np.asarray(X_blue), y, test_size=0.20, random_state=1)
    X_blue_train, X_blue_validation, y_blue_train, y_blue_validation = train_test_split(X_blue_train, y_blue_train, test_size=0.25, random_state=1)
    
    print("Finished")
    return X_red_train, X_red_test, X_red_validation, X_green_train, X_green_test, X_green_validation, X_blue_train, X_blue_test, X_blue_validation, y_blue_train, y_blue_test, y_blue_validation

Starting...
[[1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 ...
 [0 0 0 0 0 1]
 [0 0 0 0 0 1]
 [0 0 0 0 0 1]]
Finished
[[0 0 0 0 0 1]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 ...
 [0 1 0 0 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [15]:
# Call process_files and assign variables
X_red_train, X_red_test, X_red_validation, X_green_train, X_green_test, X_green_validation, X_blue_train, X_blue_test, X_blue_validation, y_train, y_test, y_validation = process_files(data_path)

# Fit/train train-datasets and store prediction vectors in variables
from sklearn import svm
from sklearn.neural_network import MLPClassifier

# Red
mlpc_red =  MLPClassifier(hidden_layer_sizes=(576), activation='relu', solver='adam')
vector_reds = mlpc_red.fit(X_red_train, y_train)
vector_red = mlpc_red.predict(X_red_train)

# Green

mlpc_green = MLPClassifier(hidden_layer_sizes=(576), activation='relu', solver='adam')
vector_greens = mlpc_green.fit(X_green_train, y_train)
vector_green = mlpc_blue.predict(X_green_train)
# Blue
mlpc_blue = MLPClassifier(hidden_layer_sizes=(576), activation='relu', solver='adam')
vector_blues = mlpc_blue.fit(X_blue_train, y_train)
vector_blue = mlpc_blue.predict(X_blue_train)

composite_vector = np.stack((vector_red, vector_green, vector_blue))



print(composite_vector)


Starting...
[[1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 ...
 [0 0 0 0 0 1]
 [0 0 0 0 0 1]
 [0 0 0 0 0 1]]
Finished
[[[1 1 0 0 0 0]
  [0 1 0 0 0 0]
  [0 0 0 0 1 0]
  ...
  [0 0 0 1 0 0]
  [0 1 0 0 0 0]
  [0 0 0 0 1 0]]

 [[1 0 0 0 0 0]
  [0 0 0 0 0 1]
  [0 0 0 1 0 1]
  ...
  [0 0 0 1 0 1]
  [0 1 0 0 0 0]
  [0 0 0 1 0 1]]

 [[1 0 0 0 0 0]
  [0 0 0 0 0 1]
  [0 0 0 0 1 0]
  ...
  [0 0 0 1 0 0]
  [0 1 0 0 0 0]
  [0 0 0 0 1 0]]]


In [ ]:
# Performance metrics
from sklearn.metrics import classification_report,confusion_matrix

print(confusion_matrix(y_train,predict_train))
print(classification_report(y_train,predict_train))